name: Update CodeChef Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch CodeChef Stats
        run: |
          curl -s "https://competitive-coding-api.herokuapp.com/api/codechef/madhunadh" > codechef.json
          RATING=$(jq -r '.rating' codechef.json)
          STARS=$(jq -r '.stars' codechef.json)
          GLOBAL_RANK=$(jq -r '.global_rank' codechef.json)
          COUNTRY_RANK=$(jq -r '.country_rank' codechef.json)
          echo "## 🍜 CodeChef Stats" > README.md
          echo "⭐ Rating: $RATING ($STARS)" >> README.md
          echo "🌍 Global Rank: $GLOBAL_RANK" >> README.md
          echo "🇮🇳 Country Rank: $COUNTRY_RANK" >> README.md
          rm codechef.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated CodeChef Stats [Automated]"
          git push
